repository:
  name: DCM-Uni-Paderborn/UZH-protocol
  url: https://github.com/DCM-Uni-Paderborn/UZH-protocol

cp2k_data_source:
  local_path: /Users/tkuehne/dropbox/cp2k_VScode/cp2k
  git_commit: 5ce8c4d8426e
  deposited_files:
    - cp2k-data/BASIS_MOLOPT_UZH
    - cp2k-data/BASIS_ADMM_UZH
    - cp2k-data/POTENTIAL_UZH

workflow_software:
  cp2k: to_be_added
  sirius: to_be_added
  aiida_core: to_be_added
  aiida_common_workflows: to_be_added
  plotting_environment: to_be_added

